module Rex
module Post
module Meterpreter
module Extensions
module MSFMap
# TLVS
TLV_TYPE_MSFMAP_GENERIC_RESPONSE    	= TLV_META_TYPE_STRING 	| (TLV_EXTENSIONS + 2)
TLV_TYPE_MSFMAP_THREAD_HOLDER_LOCATION	= TLV_META_TYPE_UINT	| (TLV_EXTENSIONS + 3)
TLV_TYPE_MSFMAP_IPADDRESSES				= TLV_META_TYPE_RAW 	| (TLV_EXTENSIONS + 4)
TLV_TYPE_MSFMAP_PORTS_SPECIFICATION		= TLV_META_TYPE_RAW		| (TLV_EXTENSIONS + 5)
TLV_TYPE_MSFMAP_SCAN_OPTIONS			= TLV_META_TYPE_UINT	| (TLV_EXTENSIONS + 6)
TLV_TYPE_MSFMAP_RETURN_FLAGS			= TLV_META_TYPE_UINT	| (TLV_EXTENSIONS + 7)

TLV_TYPE_MSFMAP_PORTS_OPEN				= TLV_META_TYPE_RAW		| (TLV_EXTENSIONS + 8)
TLV_TYPE_MSFMAP_PORTS_CLOSED			= TLV_META_TYPE_RAW		| (TLV_EXTENSIONS + 9)

# Option Flags:
# Explanation:
#	bits 0-3	Scan type
#	bits 4-6	Timing profile
#	bits 7		Ping
#	bits 8-31	reserved
MSFMAP_OPTS_SCAN_TYPE_FLAGS			= 0xf0000000
MSFMAP_OPTS_SCAN_TYPE_TCP_CONNECT	= 0x10000000
MSFMAP_OPTS_SCAN_TYPE_PING			= 0x20000000
MSFMAP_OPTS_TIMING_FLAGS			= 0x0e000000
MSFMAP_OPTS_TIMING_0				= 0x02000000
MSFMAP_OPTS_TIMING_1				= 0x04000000
MSFMAP_OPTS_TIMING_2				= 0x06000000
MSFMAP_OPTS_TIMING_3				= 0x08000000
MSFMAP_OPTS_TIMING_4				= 0x0a000000
MSFMAP_OPTS_TIMING_5				= 0x0c000000
MSFMAP_OPTS_PING 					= 0x01000000

# Return Value Flags
MSFMAP_RET_HOST_UP  		= 0x1

MSFMAP_RET_ERROR_FLAGS		= 0xffff0000
MSFMAP_RET_MEM_ERR 			= 0x20000

end
end
end
end
end
