module Rex
module Post
module Meterpreter
module Extensions
module MSFMap
# TLVS
TLV_TYPE_MSFMAP_GENERIC_RESPONSE    	= TLV_META_TYPE_STRING 	| (TLV_EXTENSIONS + 2)
TLV_TYPE_MSFMAP_THREAD_HOLDER_LOCATION	= TLV_META_TYPE_UINT	| (TLV_EXTENSIONS + 3)
TLV_TYPE_MSFMAP_IPADDRESSES				= TLV_META_TYPE_RAW 	| (TLV_EXTENSIONS + 4)
TLV_TYPE_MSFMAP_PORTS_SPECIFICATION		= TLV_META_TYPE_RAW		| (TLV_EXTENSIONS + 5)
TLV_TYPE_MSFMAP_SCAN_OPTIONS			= TLV_META_TYPE_UINT	| (TLV_EXTENSIONS + 6)
TLV_TYPE_MSFMAP_RETURN_FLAGS			= TLV_META_TYPE_UINT	| (TLV_EXTENSIONS + 7)

TLV_TYPE_MSFMAP_PORTS_OPEN				= TLV_META_TYPE_RAW		| (TLV_EXTENSIONS + 8)
TLV_TYPE_MSFMAP_PORTS_CLOSED			= TLV_META_TYPE_RAW		| (TLV_EXTENSIONS + 9)

# Option Flags:
MSFMAP_OPTS_PING 		= 0x1000000

# Return Value Flags
MSFMAP_RET_HOST_UP  	= 0x1

MSFMAP_RET_ERROR_FLAGS 	= 0xffff0000
MSFMAP_RET_MEM_ERR 		= 0x20000

end
end
end
end
end
