#ifndef _METERPRETER_SOURCE_EXTENSION_MSFMAP_MSFMAP_H
#define _METERPRETER_SOURCE_EXTENSION_MSFMAP_MSFMAP_H

#define TLV_TYPE_EXTENSION_MSFMAP	0

#define TLV_TYPE_MSFMAP_GENERIC_RESPONSE		\
		MAKE_CUSTOM_TLV(						\
				TLV_META_TYPE_STRING,			\
				TLV_TYPE_EXTENSION_MSFMAP,		\
				TLV_EXTENSIONS + 2)

#define TLV_TYPE_MSFMAP_THREAD_HOLDER_LOCATION	\
		MAKE_CUSTOM_TLV(						\
				TLV_META_TYPE_UINT,				\
				TLV_TYPE_EXTENSION_MSFMAP,		\
				TLV_EXTENSIONS + 3)

#define TLV_TYPE_MSFMAP_IPADDRESSES				\
		MAKE_CUSTOM_TLV(						\
				TLV_META_TYPE_RAW,				\
				TLV_TYPE_EXTENSION_MSFMAP,		\
				TLV_EXTENSIONS + 4)

#define TLV_TYPE_MSFMAP_PORTS_SPECIFICATION		\
		MAKE_CUSTOM_TLV(						\
				TLV_META_TYPE_RAW,				\
				TLV_TYPE_EXTENSION_MSFMAP,		\
				TLV_EXTENSIONS + 5)

#define TLV_TYPE_MSFMAP_SCAN_OPTIONS			\
		MAKE_CUSTOM_TLV(						\
				TLV_META_TYPE_UINT,				\
				TLV_TYPE_EXTENSION_MSFMAP,		\
				TLV_EXTENSIONS + 6)

#define TLV_TYPE_MSFMAP_RETURN_FLAGS			\
		MAKE_CUSTOM_TLV(						\
				TLV_META_TYPE_UINT,				\
				TLV_TYPE_EXTENSION_MSFMAP,		\
				TLV_EXTENSIONS + 7)


#define TLV_TYPE_MSFMAP_PORTS_OPEN				\
		MAKE_CUSTOM_TLV(						\
				TLV_META_TYPE_RAW,				\
				TLV_TYPE_EXTENSION_MSFMAP,		\
				TLV_EXTENSIONS + 8)

#define TLV_TYPE_MSFMAP_PORTS_CLOSED			\
		MAKE_CUSTOM_TLV(						\
				TLV_META_TYPE_RAW,				\
				TLV_TYPE_EXTENSION_MSFMAP,		\
				TLV_EXTENSIONS + 9)

#endif