/*
 * This file contains a bunch of define statements to make
 * tuning the "timing profiles" of the scanner easier by
 * keeping them all in one place.
 */

#define TIMING_PROFILE_0_PING_RETRIES 4
#define TIMING_PROFILE_0_CONNECT_TIMEOUT_SEC 2
#define TIMING_PROFILE_0_CONNECT_TIMEOUT_USEC 500
#define TIMING_PROFILE_0_NUMBER_OF_THREADS 4

#define TIMING_PROFILE_1_PING_RETRIES 3
#define TIMING_PROFILE_1_CONNECT_TIMEOUT_SEC 2
#define TIMING_PROFILE_1_CONNECT_TIMEOUT_USEC 250
#define TIMING_PROFILE_1_NUMBER_OF_THREADS 8

#define TIMING_PROFILE_2_PING_RETRIES 3
#define TIMING_PROFILE_2_CONNECT_TIMEOUT_SEC 1
#define TIMING_PROFILE_2_CONNECT_TIMEOUT_USEC 750
#define TIMING_PROFILE_2_NUMBER_OF_THREADS 16

#define TIMING_PROFILE_3_PING_RETRIES 3
#define TIMING_PROFILE_3_CONNECT_TIMEOUT_SEC 1
#define TIMING_PROFILE_3_CONNECT_TIMEOUT_USEC 250
#define TIMING_PROFILE_3_NUMBER_OF_THREADS 32

#define TIMING_PROFILE_4_PING_RETRIES 2
#define TIMING_PROFILE_4_CONNECT_TIMEOUT_SEC 1
#define TIMING_PROFILE_4_CONNECT_TIMEOUT_USEC 0
#define TIMING_PROFILE_4_NUMBER_OF_THREADS 64

#define TIMING_PROFILE_5_PING_RETRIES 2
#define TIMING_PROFILE_5_CONNECT_TIMEOUT_SEC 0
#define TIMING_PROFILE_5_CONNECT_TIMEOUT_USEC 750
#define TIMING_PROFILE_5_NUMBER_OF_THREADS 128
